import { Header } from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lato } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ weight : ["400", "900" , "700"] , subsets : ["latin"]});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout(props: { children?: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <div className="relative top-0 left-0 w-full h-full">
          <Header />
          <div className="w-full h-full relative">{props.children}</div>
        </div>
      </body>
    </html>
  );
}
